---
- name: Create (or delete) a tenant in ACI
  hosts:  ACI
  connection: local
  gather_facts: no

  tasks:
    - name: Create (or delete) tenant
      hostname: '{{ inventory_hostname }}'
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      aci_tenant:
        tenant: Ansible_Tenant
        description: 'created with ansible'
        state: present
