---

- name: IOS_Netflow_Exporter_Mod
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ios | show ip interfaces
      ios_command:
          commands: 
             - sho ip int brief | inc [0-9]+[ ]+YES
      register: ipint
    
    - set_fact:
        intf: |
          {{ipint.stdout_lines[0] |
            map('regex_findall','^([A-Za-z]+[0-9./]+)') |
            map('join') | list }}    
            
    - name: IOS | Remove flow monitor from Interface
      ios_config:
          lines: 
             - no ip flow monitor UDP-Monitor input 
             - no ip flow monitor UDP-Monitor out
          parents: "interface {{ item }}"
      with_items: "{{ intf }}"

    - name: IOS | Change Exporter IP
      ios_config:
          lines: 
             - destination 2.2.2.2
          parents: flow exporter UDP-Exporter

    - name: IOS | Add flow monitor to Interface
      ios_config:
          lines: 
             - ip flow monitor UDP-Monitor input
             - ip flow monitor UDP-Monitor out
          parents: "interface {{ item }}"
      with_items: "{{intf}}"
          
    - name: NXOS | Save to Startup
      ios_command:
          commands: 
             - wr  mem         
    - debug: var=intf
