---
- name: test
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ios | show ip interfaces
      ios_command:
          commands: 
             - sho ip int brief | sec Interface
      register: ipint
 
    - name: generate fact from interface output
      set_facts:
        nxos_ifaces: "{{ ipint.stdout[0] |parse_cli('./show_interface_parser.yml') }}"
