---

- name: Vlan Interface configuration
  hosts: '5672'
  connection: local
  gather_facts: no

  tasks:
    - name: Vlan Interface configuration
      nxos_interface:
          interface: vlan 10
          admin_state: up
          mode: layer3
          state: present
